SERVER = 'http://127.0.0.1:8000/'
BROWSER = 'chrome'
TITLE = 'PMDB'
DELAY = 0
VALID_USER = 'dabro'
VALID_PASSWORD = 'dupa123'
INVALID_USER = 'dabro123'
INVALID_PASSWORD = 'dupa321'
LOGIN_URL = SERVER
WELCOME_URL = 'http://{}/projects/'.format(LOGIN_URL)
HEADER = 'Project Management Database'
DESCRIPTION = 'Application for License-In and R&D projects, unified solution to collect data, manage harmonograms and budgets, track progress, archive data. All in one place.'
NEW_USER_NAME = 'New'
NEW_USER_LAST_NAME = 'User'
NEW_USER_EMAIL = 'new.user@adamed.com'
NEW_USER_PASS = 'newadmin123'
## Elements ##
H1_PMDB = 'xpath: //h1[@class="header"]'
P_DESC = 'xpath: //p[@class="description"]'
BUTTON_DOC = 'xpath: //span[@class="icon documentation-icon"]/parent::button'
BUTTON_CONTACT = 'xpath: //span[@class="icon contact-icon"]/parent::button'
BUTTON_SIGNIN = 'xpath://button[@id="signInDropdownMenuButton"]'
INPUT_USER = 'xpath://input[@id="id_username"]'
INPUT_PASS = 'xpath://input[@id="id_password"]'
BUTTON_LOGIN = 'xpath: //*[contains(text(), "Log in")]'
DIV_ALERT = 'xpath://div[@class="alert alert-info"]'
IMG_PROJECTS = 'xpath: //img[@title="Projects"]'
A_FORGOT = 'xpath: //*[contains(text(), "Forgot Password?")]'
A_CREATE = 'xpath: //*[contains(text(), "Create an account")]'
INPUT_FNAME = 'xpath: //input[@placeholder="First Name"]'
INPUT_LNAME = 'xpath: //input[@placeholder="Last Name"]'
INPUT_EMAIL = 'xpath: //input[@placeholder="Email"]'
BUTTON_SIGNUP = 'xpath: //button[@id="signUpDropdownMenuButton"]'
BUTTON_SIGNUP2 = 'xpath: //button[@type="submit"][contains(text(), "Sign up")]'